"use strict";


export const WS_META_CLIENT_ADD = "WS_META_CLIENT_ADD";
export const WS_META_CLIENT_REMOVE = "WS_META_CLIENT_REMOVE";
export const WS_META_CLIENT_GET = "WS_META_CLIENT_GET";
export const WS_META_CLIENT_GET_ALL = "WS_META_CLIENT_GET_ALL";
export const WS_DATA_TEXT_MESSAGE = "WS_TEXT_MESSAGE";
export const WS_DATA_BINARY_MESSAGE = "WS_BINARY_MESSAGE";

// Error constants
WS_ERR_NO_ORIGIN = "WS_ERR_NO_ORIGIN" 
let ERR = {
    WS_ERR_NO_ORIGIN : WS_ERR_NO_ORIGIN
}


// description of error constants
let ERR_DESC = {}
ERR_DESC[WS_ERR_NO_ORIGIN] = "The source of the message is not present";



module.exports = {
    WS_META_CLIENT_ADD: WS_META_CLIENT_ADD,
    WS_META_CLIENT_REMOVE: WS_META_CLIENT_REMOVE,
    WS_META_CLIENT_GET: WS_META_CLIENT_GET,
    WS_META_CLIENT_GET_ALL: WS_META_CLIENT_GET_ALL,
    WS_DATA_TEXT_MESSAGE: WS_DATA_TEXT_MESSAGE,
    WS_DATA_BINARY_MESSAGE: WS_DATA_BINARY_MESSAGE,
    ERR: ERR,
    ERR_DESC: ERR_DESC
};