module.exports = {
    WS_META_CLIENT_ADD: "WS_META_CLIENT_ADD",
    WS_META_CLIENT_REMOVE: "WS_META_CLIENT_REMOVE",
    WS_META_CLIENT_GET: "WS_META_CLIENT_GET",
    WS_META_CLIENT_GET_ALL: "WS_META_CLIENT_GET_ALL",
    WS_DATA_TEXT_MESSAGE: "WS_TEXT_MESSAGE",
    WS_DATA_BINARY_MESSAGE: "WS_BINARY_MESSAGE"
}